version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3310:3306
    user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
